### ISSUE TITLE
第一次不显示悬浮窗问题

### ISSUE THREAD

**Issue by Hemione521** [princekin-f/EasyFloat#102]
第一次安装App时，我在启动页点击一个按钮的时候选择App环境，然后这个时候因为没有权限所以跳转到权限开启页面，然后点返回的时候，我代码有个操作是跳转到MainActivity。但是我这样第一次不会显示悬浮窗，得关闭App后再打开才能显示，请问这个如何解决呢？

**Comment by princekin-f** [comment]
- 如果可以的话，在MainActivity创建；
- 申请权限时是用无视图的Fragment去申请的，申请之后有个小延时才创建的；
- 你直接关闭了启动页，可能还没执行创建；
- 或者，打开MainActivity时，延时关闭启动页。

**Comment by Hemione521** [comment]
我刚才看了下是PermissionFragment这个类申请的吧，我试下上面的方案，谢谢大佬

**Comment by Hemione521** [comment]
我试了下，延时5s关闭第一次也没显示
代码是这样：
`if (BuildConfig.DEBUG) {
            showLogViewFloatButton();
        }
        Intent intent = new Intent(this, MainTabActivity.class);
        startActivity(intent);
        overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                finish();
            }
        }, 5000);`

**Comment by princekin-f** [comment]
你试下不关闭，不做其他处理，单纯的创建显不显示。

**Comment by Hemione521** [comment]
> 你试下不关闭，不做其他处理，单纯的创建显不显示。

我现在去掉了finish这句操作，依然不显示。

**Comment by princekin-f** [comment]
用demo第一次授权后，也不创建吗？

**Comment by Hemione521** [comment]
> 用demo第一次授权后，也不创建吗？

demo在MainActivity授权，可以创建；
如果我不进行跳转的话，我在SplashActivity界面也可以创建出来；但是加入了跳转操作，就不行了，这个有可能和启动模式有关系吗？

**Comment by princekin-f** [comment]
拿到创建（成功或失败）结果再跳转，提前跳转到新页面，不回调权限申请的onActivityResult。

**Comment by Hemione521** [comment]
> 拿到创建（成功或失败）结果再跳转，提前跳转到新页面，不回调权限申请的onActivityResult。

我写写试试
