### ISSUE TITLE
应用内所有页面悬浮也需要申请权限

### ISSUE THREAD

**Issue by malonecoder** [princekin-f/EasyFloat#104]
可以有一种模式只在app中所有的页面内显示，而且不需要申请权限吗？我们只需要在应用内的所有页面悬浮显示就行了

**Comment by princekin-f** [comment]
并没有，谷歌粑粑没提供这样的窗口类型🙃

**Comment by malonecoder** [comment]
大神你好~ 用你的悬浮做了两个项目了 真心感谢大神， 但是我看有的文章说应用内悬浮不需要权限的~依赖于activity 所以切换页面的时候需要切换悬浮球的token 这样是不是会界面闪一下啊

**Comment by princekin-f** [comment]
是的，有那么实现的，记录位置，在每个页面的相同位置都创建一下；但本文不是，你也可以稍加改动这么实现，但确实会闪一下。

**Comment by princekin-f** [comment]
微信的悬浮窗，也需要权限申请，确实没什么好的办法，实现应用内浮窗。

**Comment by malonecoder** [comment]
好 知道了谢谢啦~

**Comment by MhuiHugh** [comment]
换这个框架 https://github.com/Petterpx/FloatingX 应用内不要权限
