### ISSUE TITLE
下层事件

### ISSUE THREAD

**Issue by haoxiongqin** [princekin-f/EasyFloat#106]
怎么去触摸监听悬浮窗下层的事件

**Comment by princekin-f** [comment]
- 设置子view的触摸监听（setOnTouchListener）；
- 或者重写子view的触摸事件（onTouchEvent）；
- 子view优先享用触摸事件的话，可以动态设置浮窗是否可拖拽（xxDragEnable），或者禁用拖拽父控件的拦截（requestDisallowInterceptTouchEvent）。
