### ISSUE TITLE
拖动完成如何设置新布局

### ISSUE THREAD

**Issue by vincentleezebra** [princekin-f/EasyFloat#107]
需求：
1.初始状态，半圆吸附在右侧。
2.拖动状态，变成圆形
3.拖动完成，半圆吸附在右侧或左侧（根据拖动结束位置判断）

![QQ图片20200911171543](https://user-images.githubusercontent.com/10320862/92900958-b33f7f00-f452-11ea-8a88-33d8f944bb35.png)

![move](https://user-images.githubusercontent.com/10320862/92901132-d407d480-f452-11ea-98b8-89bc7f6c5aa1.png)

通过visibility控制拖动后的布局显示，左边布局宽度显示异常。
![left](https://user-images.githubusercontent.com/10320862/92901963-7b850700-f453-11ea-866c-2d3cd9681e88.png)

float_custom.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/ll_root"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <TextView
        android:visibility="gone"
        android:id="@+id/tv_move"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:background="@drawable/corners_oval"
        android:gravity="center"
        android:text="拖动"
        android:textColor="@color/white"
        android:textSize="16sp" />

    <TextView
        android:visibility="gone"
        android:id="@+id/tv_right"
        android:layout_width="120dp"
        android:layout_height="60dp"
        android:background="@drawable/corners_right"
        android:gravity="center"
        android:text="左边"
        android:textColor="@color/white"
        android:textSize="16sp" />

    <TextView
        android:visibility="visible"
        android:id="@+id/tv_left"
        android:layout_width="120dp"
        android:layout_height="60dp"
        android:background="@drawable/corners_left"
        android:gravity="center"
        android:text="右边"
        android:textColor="@color/white"
        android:textSize="16sp" />
</LinearLayout>`

 `private fun showActivityFloat() {

        EasyFloat.with(this)
            .setSidePattern(SidePattern.RESULT_HORIZONTAL)
            .setGravity(Gravity.END, 0, 100)
            .setLayout(R.layout.float_custom, OnInvokeView {
            })
            .registerCallback {
                createResult { isCreated, msg, _ -> logger.e("DSL:  $isCreated   $msg") }

                drag { view, _ ->
                    view.findViewById<TextView>(R.id.tv_move).apply {
                        visibility=View.VISIBLE;
                    }
                    view.findViewById<TextView>(R.id.tv_right).apply {
                        visibility=View.GONE;
                    }
                    view.findViewById<TextView>(R.id.tv_left).apply {
                        visibility=View.GONE;
                    }
                }

                dragEnd {

                    it.findViewById<LinearLayout>(R.id.ll_root).apply {
                        val location = IntArray(2)
                        getLocationOnScreen(location)
                        if (location[0] > 0){
                            it.findViewById<TextView>(R.id.tv_move).apply {
                                visibility=View.GONE;
                            }
                            it.findViewById<TextView>(R.id.tv_right).apply {
                                visibility=View.GONE;
                            }
                            it.findViewById<TextView>(R.id.tv_left).apply {
                                visibility=View.VISIBLE;
                            }

                        }else{
                            it.findViewById<TextView>(R.id.tv_move).apply {
                                visibility=View.GONE;
                            }
                            it.findViewById<TextView>(R.id.tv_right).apply {
                                visibility=View.VISIBLE;
                            }
                            it.findViewById<TextView>(R.id.tv_left).apply {
                                visibility=View.GONE;
                            }
                        }
                    }
                }
            }
            .show()
    }`

![left](https://user-images.githubusercontent.com/10320862/92901933-7758e980-f453-11ea-86b3-c1c0231e46a6.png)
怎么解决左边布局显示不全？thk

**Comment by princekin-f** [comment]
https://github.com/princekin-f/EasyFloat/issues/124
