### ISSUE TITLE
希望能开放出 申请权限的方法

### ISSUE THREAD

**Issue by HMZhhh** [princekin-f/EasyFloat#11]
/**
     * 申请悬浮窗权限
     */
    internal fun requestPermission(activity: Activity, onPermissionResult: OnPermissionResult) {
        PermissionFragment.requestPermission(activity, onPermissionResult)
    }
就是这个方法啦 因为想在开始 就引导用户开启  而不是在触发的时候 使用  有时候 权限回调 并没有回来 。。。

**Comment by princekin-f** [comment]
- 好的，把`internal`修饰符去掉就可以了；
- 你后面说，权限回调没有回来是什么情况？

**Comment by HMZhhh** [comment]
修饰符 我本地导入改了  回调我看了下我的代码 是这样的   由于还有其他管理 所以 将初始化放在 了 homeActivity  而触发easyDialog 可能是其他的界面 就这样 第一次的时候 权限申请的 那个 回调 就会 卡住 。。。

**Comment by princekin-f** [comment]
- 不是很懂你的描述
- 权限申请对外暴露的就是一个接口，存在的情况无外乎（正常回调、回调不正常、不回调）
- 这个回调卡住是什么鬼...
