### ISSUE TITLE
如何设置自定义view类进去

### ISSUE THREAD

**Issue by lwx123** [princekin-f/EasyFloat#110]
比如MyView myView = new MyView(this);
怎么把这个view添加进去(不想建xml文件)：
EasyFloat.with(this).setLayout(       myView      ).show();

**Comment by quelleG** [comment]
我用复合控件解决了这个问题

**Comment by gdoudeng** [comment]
@quelleG 老哥怎么解决的

**Comment by princekin-f** [comment]
v 2.0.3  现已支持，感谢反馈。
