### ISSUE TITLE
异常导致闪退：java.lang.IllegalArgumentException: View=com.lzf.easyfloat.widget.appfloat.ParentFrameLayout  not attached to window manager

### ISSUE THREAD

**Issue by xiasang920** [princekin-f/EasyFloat#111]
详细报错：
09-21 11:24:20.417 E/AndroidRuntime(16458): java.lang.IllegalArgumentException: View=com.lzf.easyfloat.widget.appfloat.ParentFrameLayout{df9962b VFE...C.. ...P..ID 0,0-226,257} not attached to window manager
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:547)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:422)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:153)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at com.lzf.easyfloat.widget.appfloat.TouchUtils$sideAnim$1.onAnimationUpdate(TouchUtils.kt:223)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.Choreographer.doFrame(Choreographer.java:809)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.os.Handler.handleCallback(Handler.java:907)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.os.Looper.loop(Looper.java:216)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at java.lang.reflect.Method.invoke(Native Method)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
09-21 11:24:20.417 E/AndroidRuntime(16458): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

求助，要怎么解呢这个

**Comment by princekin-f** [comment]
已处理（v`1.3.4`）
