### ISSUE TITLE
拖拽之后如何获取悬浮窗的位置

### ISSUE THREAD

**Issue by Super-Brother** [princekin-f/EasyFloat#12]
拖拽之后如何获取悬浮窗的位置

**Comment by princekin-f** [comment]
- 通过`registerCallbacks`可以获取各种状态回调；

- `touchEvent(View, MotionEvent)`：是将对浮窗的touch事件进行转发，我们可以对touch事件做二次开发；
- `dragEnd(View)`：这是拖拽结束的回调，返回的是浮窗View，我们可以通过View得到各种坐标数据，如`view.getLocationOnScreen()`获取在屏幕的绝对坐标，以及其他各种坐标；
- 坐标获取可以参考一下这个：[Android 应用坐标系统全面详解](https://juejin.im/entry/5768e765816dfa005475eda5)

**Comment by qq860694896** [comment]
好的,多谢了

**Comment by qq860694896** [comment]
touch事件为啥不能return true/false

**Comment by princekin-f** [comment]
- Callback里面touch事件，只是touch事件的中转，告诉我们手指在屏幕做了哪些操作，和内部的拖拽逻辑互不干扰；
- **由于拖拽逻辑必须用到touch事件，所以第一手的touch事件，肯定是要给到浮窗的；**
- **如有你想优先于浮窗，先去处理touch事件，需要屏蔽掉浮窗的事件拦截。**

demo中的浮窗缩放，就是优先处理touch的一个例子：
```
// 屏蔽掉浮窗的事件拦截，仅由自身消费
parent?.requestDisallowInterceptTouchEvent(true)
```

或者说你想实现什么样的需求，我们一起想办法...

**Comment by qq860694896** [comment]
感觉你人超不错啊 加个微信吧qq860694896

**Comment by qq860694896** [comment]
我们现在的业务需求是悬浮窗三秒后隐藏一半进去

**Comment by Mc-dashan** [comment]
兄弟，我们的需求也差不多是这个，介意分享一下怎么弄的吗？
