### ISSUE TITLE
EasyFloat 拖动位置后,获取位置参数

### ISSUE THREAD

**Issue by malonecoder** [princekin-f/EasyFloat#121]
大神你好 一直在用你的框架，EasyFloat可以获取config信息吗，我们需要根据floatView gravity在屏幕的上下左右位置去显示不同的UI菜单，感谢~

**Comment by malonecoder** [comment]
我通过drag方法  滑动x是否大于屏幕/2 来判断的左右，这样应该可以吧

**Comment by princekin-f** [comment]
可以

**Comment by dyguests** [comment]
dragEnd {
                    it.findViewById<TextView>(R.id.textView).apply {
                        text = "拖拽结束"
                        val location = IntArray(2)
                        getLocationOnScreen(location)
                        setBackgroundResource(if (location[0] > 10) R.drawable.corners_left else R.drawable.corners_right)
                    }
                }

找到示例代码中的方法了
