### ISSUE TITLE
物理返回键监听不到的bug

### ISSUE THREAD

**Issue by songyuxianggood** [princekin-f/EasyFloat#122]
常规的popwindow等window都能监听到物理返回键，你这代码的window监听不到，初步定为是ParentFrameLayout的实现有问题

**Comment by princekin-f** [comment]
- ？？，悬浮窗为什么要监听返回键，浮窗把事件都消费了，难道不影响正常业务吗？
- 浮窗的生杀大权应该统一管理（Activity等）
- 另外，是否监听返回键由window的flags属性决定，和内部view无关。
