### ISSUE TITLE
Activity内使用悬浮窗，点击需要隐藏一些View，然后再拖动到屏幕边缘，点击显示所隐藏的view，这时隐藏的view会在屏幕外显示

### ISSUE THREAD

**Issue by zhangliuguang** [princekin-f/EasyFloat#124]
Activity内使用悬浮窗，点击需要隐藏一些View，然后再拖动到屏幕边缘，点击显示所隐藏的view，这时隐藏的view会在屏幕外显示

**Comment by princekin-f** [comment]
更新到最新版`v2.0.1`，显示隐藏后调用`EasyFloat.updateFloat(tag)`，会重新吸附

**Comment by qq2748** [comment]
2.0.4还不行啊
