### ISSUE TITLE
空指针导致app闪退

### ISSUE THREAD

**Issue by zzzsssbo** [princekin-f/EasyFloat#128]
虽然我看到源码里边try catch了异常，但是偶尔还是会出现闪退的情况，能否在readLine之前判空处理一下。
日志如下：
03-02 02:40:39.056 21247 21247 E AndroidRuntime: Caused by: java.lang.IllegalStateException: input.readLine() must not be null
--
5103-02 02:40:39.056 21247 21247 E AndroidRuntime: at com.lzf.easyfloat.permission.rom.RomUtils.getSystemProperty(RomUtils.kt:58)
5203-02 02:40:39.056 21247 21247 E AndroidRuntime: at com.lzf.easyfloat.permission.rom.RomUtils.checkIsMeizuRom(RomUtils.kt:80)
5303-02 02:40:39.056 21247 21247 E AndroidRuntime: at com.lzf.easyfloat.permission.PermissionUtils.commonROMPermissionCheck(PermissionUtils.kt:77)
5403-02 02:40:39.056 21247 21247 E AndroidRuntime: at com.lzf.easyfloat.permission.PermissionUtils.checkPermission(PermissionUtils.kt:38)

**Comment by princekin-f** [comment]
好的，感谢反馈，之前只try catch了IOException，处理不了空指针
