### ISSUE TITLE
2.0.1和SuperTextView 冲突了

### ISSUE THREAD

**Issue by ithomasoft** [princekin-f/EasyFloat#131]
shapeType 自定义属性

SuperTextView
        <attr format="enum" name="shapeType">
            <enum name="rectangle" value="0"/>
            <enum name="oval" value="1"/>
            <enum name="line" value="2"/>
            <enum name="ring" value="3"/>
        </attr>

<declare-styleable name="DefaultCloseView">
        
        <attr name="normalColor" format="color" />
        
        <attr name="inRangeColor" format="color" />
        
        <attr name="shapeType" format="enum">
            <enum name="oval" value="0" />
            <enum name="rect" value="1" />
            <enum name="circle" value="2" />
        </attr>
        
        <attr name="zoomSize" format="dimension" />
    </declare-styleable>

**Comment by ithomasoft** [comment]
<declare-styleable name="DefaultCloseView">
        
        <attr name="normalColor" format="color" />
        
        <attr name="inRangeColor" format="color" />
        
        <attr name="shapeType" format="enum">
            <enum name="oval" value="0" />
            <enum name="rect" value="1" />
            <enum name="circle" value="2" />
        </attr>
        
        <attr name="zoomSize" format="dimension" />
    </declare-styleable>

**Comment by ithomasoft** [comment]
、、、<declare-styleable name="DefaultCloseView">
        
        <attr name="normalColor" format="color" />
        
        <attr name="inRangeColor" format="color" />
        
        <attr name="shapeType" format="enum">
            <enum name="oval" value="0" />
            <enum name="rect" value="1" />
            <enum name="circle" value="2" />
        </attr>
        
        <attr name="zoomSize" format="dimension" />
     </declare-styleable>

**Comment by ithomasoft** [comment]
代码出不来了
https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/res/values/attrs.xml

**Comment by princekin-f** [comment]
- 这是一个默认实现，不能保证和其他第三方一定没冲突；
- 重写DefaultCloseView，传入对应的布局文件即可。
