### ISSUE TITLE
activity的oncreate方法直接执行showActivityFloat无法显示

### ISSUE THREAD

**Issue by conghuahuadan** [princekin-f/EasyFloat#132]
2.0.1版本，activity的oncreate方法直接执行showActivityFloat无法显示，提示Unable to add window -- token null is not valid; is your activity running?
![image](https://user-images.githubusercontent.com/20864280/112157956-acc06a00-8c22-11eb-93e8-7cf9a3ce1d28.png)

![image](https://user-images.githubusercontent.com/20864280/112157925-a631f280-8c22-11eb-84dc-20a8d898dca0.png)

**Comment by princekin-f** [comment]
新版的单页面浮窗，和popupwindow是同一类型，需要Activity的windowToken，在onCreate直接创建可能会参数异常
- 可以将创建放在onResume
- 或者在onCreate设置个延时
- 你好像也是小刘鸭粉丝，难得😂
