### ISSUE TITLE
无法创建浮窗代码Bug

### ISSUE THREAD

**Issue by kjsolo** [princekin-f/EasyFloat#138]
在创建浮窗的时候，如果createWindow出错，会继续保存一个tag到windowMap，这样会导致下次继续show同样tag的浮窗就会因为已存在同样tag而无法创建
`windowMap[config.floatTag!!] =
            FloatingWindowHelper(context, config).apply { createWindow() }`

**Comment by princekin-f** [comment]
感谢反馈，现已修复`v 2.0.3`。
