### ISSUE TITLE
调用.registerCallbacks(new OnFloatCallbacks(){方法一直编译报错

### ISSUE THREAD

**Issue by fengzhous** [princekin-f/EasyFloat#14]
错误: 无法访问Function1
                        .registerCallbacks(new OnFloatCallbacks() {
                        ^
  找不到kotlin.jvm.functions.Function1的类文件

怎么弄都报这个，奇怪

**Comment by princekin-f** [comment]
- 这是一个重载方法，在纯Java中确实报这个错，如果项目支持kotlin就正常；
- 我很迷茫，正在想办法解决...

**Comment by princekin-f** [comment]
**这个问题和`Gradle`版本有关，可能是方法重载时的特殊处理，导致的异常情况。**

我们可以从下面几个方面着手：

- 1，使用低版本Gradle构造工具，实测正常使用；
- 2，为项目配置kotlin语言，`Tools` ->`Kotlin` ->`Configure Kotlin in Project`，实测正常使用；
- 3，`registerCallbacks`不使用方法重载，使用两个不同的方法名，没有测试，但应该可以。

比较推荐方案2，毕竟我们早晚要入kotlin的坑...

**Comment by fengzhous** [comment]
感谢耐心解答，我项目使用了你这个库就好像必须配置Kotlin，所以应该是已经配置过Kotlin的，再按你2所说的步骤去配置点击提示：All moudules with Kotlin files are configured，但是还是会报这个错误，然后我修改了这个重构的方法名字，就可以了
