### ISSUE TITLE
在service中         EasyFloat.getAppFloatView(); 获取为null

### ISSUE THREAD

**Issue by wuh876** [princekin-f/EasyFloat#143]
EasyFloat.with(this.getApplicationContext())
                .setLayout(R.layout.layout_radio)
                .setGravity(Gravity.BOTTOM)
                .setShowPattern(ShowPattern.ALL_TIME)
                .setSidePattern(SidePattern.RESULT_LEFT)
                .show();

        EasyFloat.getAppFloatView();

**Comment by princekin-f** [comment]
- 是执行完创建就获取吗？
- 在创建回调中获取，或者延时获取；本意就是获取时要确保创建完成。

**Comment by wuh876** [comment]
show完之后获取的

**Comment by princekin-f** [comment]
> show完之后获取的

- 是show完立即获取？还是创建完成获取？
- show不等于创建完成，就好比直接在activity的oncreate获取view大小无效一样

**Comment by wuh876** [comment]
show完立即获取
现在我改成在回调里获取
