### ISSUE TITLE
在service中怎么创建appfloat

### ISSUE THREAD

**Issue by wuh876** [princekin-f/EasyFloat#144]
EasyFloat.with(this).setTag("radio")
                .setLayout(R.layout.layout_radio)
                .setGravity(Gravity.BOTTOM)
                .setShowPattern(ShowPattern.ALL_TIME)
                .setSidePattern(SidePattern.RESULT_LEFT)
                .show();

这样不行呢？？？

**Comment by wuh876** [comment]
需要设置权限

**Comment by Yangqingchun** [comment]
> 需要设置权限
请问需要设置什么权限呢大佬

**Comment by wuh876** [comment]
在其他应用的上层显示
