### ISSUE TITLE
EasyFloat 拖拽问题，请问如何解决？

### ISSUE THREAD

**Issue by BatterMan-Li** [princekin-f/EasyFloat#149]
首先显示的时候把setDragEnable设置true,  setMatchParent的宽度设置（true, false）后，然后通过调用缩放功能，缩小布局宽度小于屏幕宽度后不能左右拖拽布局，如果setMatchParent(false, false)，显示出来布局没有充满屏幕宽度，此时不管不管怎么修改都可以拖拽布局
针对上面的问题我想刚显示时充满屏幕宽度，修改布局后能拖动布局，如何解决？

**Comment by princekin-f** [comment]
- 先给xml根布局设置一个很大很大的宽度，在创建完成时，手动改成屏幕宽度；
- 后续操作，就是你想干嘛就干嘛了...
- ps：前提是`setMatchParent(false, false)`，不然你操作布局没啥意义。
