### ISSUE TITLE
attr和其他项目冲突了。。。

### ISSUE THREAD

**Issue by sunlimiter** [princekin-f/EasyFloat#150]
<attr name="shapeType" format="enum">

**Comment by sunlimiter** [comment]
` <attr name="shapeType" format="enum">`

**Comment by inshyma** [comment]
代码扣下来,自己改呗, 让作者让着其他库的可能性不大

**Comment by princekin-f** [comment]
`shapeType` -> `closeShapeType`，`v2.0.4`开始替换。
