### ISSUE TITLE
创建悬浮窗以后 横屏 （或者先横屏创建悬浮窗 -》竖屏） 位置不对

### ISSUE THREAD

**Issue by wbcocos** [princekin-f/EasyFloat#151]
创建悬浮窗以后 横屏 （或者先横屏创建悬浮窗 -》竖屏） 位置不对

**Comment by princekin-f** [comment]
- 这是一个很虚的概念，比如说：一个竖屏很长的浮窗，你横屏后，屏幕高度都放不下，你说怎么适配？
- 所以这里没做适配，具体需求，具体解决！
