### ISSUE TITLE
作者你好，你的混淆配置错误了，没有把规则打包进aar

### ISSUE THREAD

**Issue by davidgerka** [princekin-f/EasyFloat#164]
如下图所示，把红框改为绿框就可以了
![image](https://user-images.githubusercontent.com/13624423/125880058-2f53a274-3e70-4382-ab81-10c08d274090.png)
可以看看这两个贴，验证一下：
https://www.jianshu.com/p/a8614ff60647
https://blog.csdn.net/zjws23786/article/details/58587289

**Comment by davidgerka** [comment]
新建一个库工程，as会自动添加混淆配置，如下图，我们应该是要用绿框这个
![image](https://user-images.githubusercontent.com/13624423/125886709-e22345b0-63c4-4179-82b8-1fe78bed9fd6.png)

**Comment by DearZack** [comment]
在库没改的前提下你是怎么解决的

**Comment by princekin-f** [comment]
> 如下图所示，把红框改为绿框就可以了
> ![image](https://user-images.githubusercontent.com/13624423/125880058-2f53a274-3e70-4382-ab81-10c08d274090.png)
> 可以看看这两个贴，验证一下：
> https://www.jianshu.com/p/a8614ff60647
> https://blog.csdn.net/zjws23786/article/details/58587289

好的，感谢分享反馈，学到了，再次感谢！

**Comment by princekin-f** [comment]
> 在库没改的前提下你是怎么解决的

可以把框架的混淆规则配到项目里：
```
# 保持配置类 config 不被混淆
-keep class com.lzf.easyfloat.data.FloatConfig {*;}

# 保持自定义控件、ContentProvider 不被混淆
-keep public class * extends android.view.View
-keep public class * extends android.content.ContentProvider

# 保持枚举 enum 类不被混淆
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# 保持反射不被混淆
-keepattributes EnclosingMethod
```

**Comment by princekin-f** [comment]
已修复`v2.0.4`。
