### ISSUE TITLE
奇怪requestPermission报错了

### ISSUE THREAD

**Issue by fengzhous** [princekin-f/EasyFloat#18]
/**
     * 申请悬浮窗权限
     */
    fun requestPermission(activity: Activity, onPermissionResult: OnPermissionResult) {
        PermissionFragment.requestPermission(activity, onPermissionResult)
    }

方法报错了，无法从静态上下文中引用非静态
我自己加上了@JvmStatic就可以了，不知道为什么Demo里的不会报错

 /**
     * 主动申请浮窗权限
     */
    private fun requestPermission() {
        PermissionUtils.requestPermission(this, object : OnPermissionResult {
            override fun permissionResult(isOpen: Boolean) {
                logger.i(isOpen)
            }
        })
    }

**Comment by princekin-f** [comment]
- 不好意思忘加了，Demo是用Kotlin写的，可以直接调用；
- 在Java中，需要先获取该类的示例：
```
PermissionUtils.INSTANCE.requestPermission()
```
- `object`其实就是对象声明，定义了该类，并且和饿汉式单例对象结合在一起；
- `@JvmStatic`注解，会让编译器在该类中生成相应的静态方法，就可以像Kotlin一样直接调用了。
