### ISSUE TITLE
横屏模式下，悬浮窗超过屏幕物理宽度后不显示

### ISSUE THREAD

**Issue by licoba** [princekin-f/EasyFloat#188]
如题，在竖屏模式下一切正常，悬浮窗在右下角有一个可以调整大小的按钮。
### 前置条件
- App只支持竖屏显示，Menifest.xml文件内配置了` android:screenOrientation="portrait"`，屏幕旋转时App不会跟着旋转
- 显示一个系统级悬浮窗，然后将本App退出到后台，进入其它支持屏幕旋转的App，例如系统浏览器
- 系统的「自动旋转屏幕打开」，App的悬浮窗悬浮在浏览器之上
- 因为需要悬浮窗可以拖动，所以设置 `EasyFloat.setMatchParent(false,false)`
- 将手机横过来
### 操作步骤
当屏幕旋转到横屏时，浏览器和悬浮窗都跟着屏幕旋转了，此时去拖动右下角的伸缩按钮进行悬浮窗的放大。
### 异常表现
悬浮窗放大到一个边界值之后，剩下的显示区域会被切割掉。
尝试发现这个边界值的规律，将悬浮窗宽度刚好调整到边界值后，再将屏幕竖过来
发现：此宽度边界值就是屏幕的物理宽度，横屏时，超过这个边界值的区域会不显示。

https://user-images.githubusercontent.com/19327381/142963679-af46a052-0330-4718-a19e-8155d925bac3.mp4

**Comment by licoba** [comment]
找到解决办法了，fork仓库，然后补充了一个方法，可以参考这里：https://github.com/licoba/EasyFloat
碰到同样问题的同学，也可以直接修改依赖为这个：`implementation 'com.github.licoba:EasyFloat:2.0.4' `
具体的做法是：在`FloatingWindowHelper`添加一个方法
```
    fun updateFloatPositionSize(x: Int, y: Int, width: Int, height: Int) {
        frameLayout?.let {
            if (x == -1 && y == -1) {
                // 未指定具体坐标，执行吸附动画
                it.postDelayed({ touchUtils.updateFloat(it, params, windowManager) }, 200)
            } else {
                params.x = x
                params.y = y
                params.width = width;
                Log.e("Helper","宽度："+width)
                windowManager.updateViewLayout(it, params)
            }
        }
    }
```
横屏时将正确的窗口宽度传入即可解决此问题

**Comment by licoba** [comment]
最新效果哈哈哈，完美了

https://user-images.githubusercontent.com/19327381/143417883-21a2abbc-ae71-49a4-9d6a-2de97b5e7faf.mp4

**Comment by LijiangOP** [comment]
赞！但都改了，为啥不把高度设置也加上。。。

**Comment by licoba** [comment]
> 赞！但都改了，为啥不把高度设置也加上。。。

是我格局小了😁只解决了这一个问题哈哈

**Comment by princekin-f** [comment]
很好👍，要启动cv大法了：
```
/**
 * 更新浮窗坐标、以及大小，未指定数值（全为-1）执行吸附动画；
 * 需要修改的参数，传入具体数值，不需要修改的参数保持-1即可
 * @param x         更新后的X轴坐标
 * @param y         更新后的Y轴坐标
 * @param width     更新后的宽度
 * @param height    更新后的高度
 */
fun updateFloat(x: Int = -1, y: Int = -1, width: Int = -1, height: Int = -1) {
    frameLayout?.let {
        if (x == -1 && y == -1 && width == -1 && height == -1) {
            // 未指定具体坐标，执行吸附动画
            it.postDelayed({ touchUtils.updateFloat(it, params, windowManager) }, 200)
        } else {
            if (x != -1) params.x = x
            if (y != -1) params.y = y
            if (width != -1) params.width = width
            if (height != -1) params.height = height
            windowManager.updateViewLayout(it, params)
        }
    }
}
```

**Comment by hzmtl** [comment]
系统浮全局浮窗那个 横竖屏切换还是有问题吧
