### ISSUE TITLE
大佬。我能不能加你好友··

### ISSUE THREAD

**Issue by sd3970566** [princekin-f/EasyFloat#19]
大佬。我能不能加你好友··

**Comment by sd3970566** [comment]
引用 模块的时候 重构出现 ERROR: Plugin with id 'kotlin-android-extensions' not found.

**Comment by princekin-f** [comment]
- 当然可以啦，下面是我的微信：
![](https://user-images.githubusercontent.com/23430080/65372780-f2574c00-dca6-11e9-9c53-dd1f648888e9.jpeg)

- 你的问题好像是没有给项目配置Kotlin的相关插件，在项目的根`build.gradle`添加依赖：
```
buildscript {
    ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        ...  // 其他配置
    }
}

... // 其他配置
```
