### ISSUE TITLE
抓到buggly上的报错

### ISSUE THREAD

**Issue by liweijieok** [princekin-f/EasyFloat#193]
kotlin.UninitializedPropertyAccessException: lateinit property params has not been initialized
android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5546)
......
kotlin.UninitializedPropertyAccessException:lateinit property params has not been initialized
com.lzf.easyfloat.core.FloatingWindowHelper.void setParams(android.view.WindowManager$LayoutParams)(FloatingWindowHelper.java:33)
com.lzf.easyfloat.core.FloatingWindowHelper.android.view.WindowManager$LayoutParams getParams()(FloatingWindowHelper.java:33)
com.lzf.easyfloat.utils.LifecycleUtils.void checkHide(android.app.Activity)(LifecycleUtils.java:85)
com.lzf.easyfloat.utils.LifecycleUtils.void access$checkHide(com.lzf.easyfloat.utils.LifecycleUtils,android.app.Activity)(LifecycleUtils.java:15)
com.lzf.easyfloat.utils.LifecycleUtils$setLifecycleCallbacks$1.void onActivityStopped(android.app.Activity)(LifecycleUtils.java:50)
android.app.Application.dispatchActivityStopped(Application.java:503)

**Comment by liweijieok** [comment]
我使用的模式是：ShowPattern.BACKGROUND

**Comment by princekin-f** [comment]
你好，请问是最新版本吗，之前的版本会存在这个问题：https://github.com/princekin-f/EasyFloat/issues/173

**Comment by liweijieok** [comment]
升级2.0.4 之后fix
