### ISSUE TITLE
使用普通的创建actitivty浮窗无法再次显示

### ISSUE THREAD

**Issue by crazyzjw** [princekin-f/EasyFloat#195]
```
EasyFloat.with(context)
                .setTag(TAG_AUDIO_FLOAT)
                .setShowPattern(ShowPattern.CURRENT_ACTIVITY)
                .setLayout(this@AudioFloatView)
                .setGravity(Gravity.RIGHT or Gravity.BOTTOM, (-12f).dpToPx(), (-118f).dpToPx())
                .setSidePattern(
                    SidePattern.RESULT_SIDE
                ).show()
```
`EasyFloat.dismiss(TAG_AUDIO_FLOAT)`

diimiss之后再走show就无法显示出来了

**Comment by princekin-f** [comment]
dismiss是销毁，hide之后可以show

**Comment by crazyzjw** [comment]
> 
dismiss之后不可以再用下面代码展示了么
```
EasyFloat.with(context)
                .setTag(TAG_AUDIO_FLOAT)
                .setShowPattern(ShowPattern.CURRENT_ACTIVITY)
                .setLayout(this@AudioFloatView)
                .setGravity(Gravity.RIGHT or Gravity.BOTTOM, (-12f).dpToPx(), (-118f).dpToPx())
                .setSidePattern(
                    SidePattern.RESULT_SIDE
                ).show()
```

**Comment by crazyzjw** [comment]
> dismiss是销毁，hide之后可以show

现在是只要我hide还是/dismiss之后再用 EasyFloat.show(TAG_AUDIO_FLOAT)/或者初始化那段代码都显示不出来

**Comment by crazyzjw** [comment]
> EasyFloat.with(context)
>                 .setTag(TAG_AUDIO_FLOAT)
>                 .setShowPattern(ShowPattern.CURRENT_ACTIVITY)
>                 .setLayout(this@AudioFloatView)
>                 .setGravity(Gravity.RIGHT or Gravity.BOTTOM, (-12f).dpToPx(), (-118f).dpToPx())
>                 .setSidePattern(
>                     SidePattern.RESULT_SIDE
>                 ).show()

这个show是用来创建的,但是EasyFloat.show(TAG_AUDIO_FLOAT)又不一样,导致有时想先创建好,再触发再显示与否就麻烦了

**Comment by lacker159** [comment]
我发现 "不设置 Tag" 和 "设置一样 Tag" 会发生这样的问题, 设置不同的 Tag 就不会出现这样的问题了.
