### ISSUE TITLE
版本升级遇到的问题

### ISSUE THREAD

**Issue by mm46468648** [princekin-f/EasyFloat#199]
原来使用的是1.3.3版本
在Application中调用了EasyFloat.init(this, DebugUtil.debugMode)
但是直接升级到2.0.4版本之后，发现这个方法没有了，请问还需要在这里初始化么

使用2.0.4版本的目的是为了使用
EasyFloat.updateFloat(LogFloatTag, width = params.width, height = params.height)
这个方法
请问如果不升级，在老版本中可以用什么方法替代么

**Comment by Jebb4ver** [comment]
> 原来使用的是1.3.3版本
> 
> 在Application中调用了EasyFloat.init(this, DebugUtil.debugMode)
> 
> 但是直接升级到2.0.4版本之后，发现这个方法没有了，请问还需要在这里初始化么
> 
> 
> 
> 使用2.0.4版本的目的是为了使用
> 
> EasyFloat.updateFloat(LogFloatTag, width = params.width, height = params.height)
> 
> 这个方法
> 
> 请问如果不升级，在老版本中可以用什么方法替代么
> 
> 

Floathasbeenfloated

**Comment by princekin-f** [comment]
不用初始化了，会在`ContentProvider`初始化。
