### ISSUE TITLE
希望能增加个允许重新setGrivity的方法

### ISSUE THREAD

**Issue by jqorz** [princekin-f/EasyFloat#20]
如果setGrivity为Grivity.End，然后布局的宽度改变了，悬浮窗就没法自动贴在屏幕右侧，仍是原来的位置。看了一下源码，希望能把AppFloatManager.setGrivaity由EasyFloat暴露出来，这样就可以手动调用

**Comment by princekin-f** [comment]
是的，由于你只是设置浮窗的宽度，并没有产生拖拽位移，所以不会有位移后的吸附动画；

两种解决方案：

1. 使用原有的吸附逻辑，就是你提到的那个方法，不过是私有的。针对你的需求，你可以本地把方法开放出来；
2. 或者在你设置宽度的时候，根据那个变化数值，写一个简单的位移动画。
