### ISSUE TITLE
OPPO R11s 必须每次创建问题

### ISSUE THREAD

**Issue by liweijieok** [princekin-f/EasyFloat#202]
我使用了showPattern为`ShowPattern.BACKGROUND`，然后到了后台展示了，回到前台使用了`EasyFloat.hide(tag)`，然后点击悬浮窗回到应用的前台，再次按下home键回到后台，这时候悬浮窗不展示了。
他需要每次都重新create悬浮窗，就是从前台到后台的时候create一个，从后台到前台的时候，需要调用`EasyFloat.dismiss(tag)`才可以

**Comment by princekin-f** [comment]
手动设置隐藏优先级较高，相当于终止自动显示隐藏的逻辑。

**Comment by liweijieok** [comment]
> 

啥意思，没太明，🤔

**Comment by princekin-f** [comment]
> 

后台模式会自动自动控制显隐，不需要手动隐藏，手动隐藏的优先级较高，会终止自动处理逻辑。
