### ISSUE TITLE
关于当退到后台的问题

### ISSUE THREAD

**Issue by woshigw** [princekin-f/EasyFloat#206]
关于app退到后台  怎么使那个悬浮按钮在拖动过程中下面显示垃圾桶  我现在按照你的demo来  当退到后台  拖动那个悬浮按钮没有显示最底部的那个垃圾桶  如果没有推倒后台就显示底部那个垃圾桶。请问是怎么回事呀。我用的是java写的代码

**Comment by princekin-f** [comment]
- demo中的垃圾桶是Activity浮窗，改成全局浮窗就可以了；
- `DragUtils.registerDragClose`可传入浮窗类别。
