### ISSUE TITLE
锁屏状态下怎么显示悬浮窗

### ISSUE THREAD

**Issue by cl549723678** [princekin-f/EasyFloat#208]

**Comment by zhengxuming** [comment]
同问，目前看到使用activity当悬浮窗可以实现在锁屏显示，作者这个实现方式试了很多种方法都不行。

**Comment by zhengxuming** [comment]
已找到实现锁屏显示的方式，需要和无障碍模式配合，关键词搜索 TYPE_ACCESSIBILITY_OVERLAY，需要改动源码。
