### ISSUE TITLE
当有状态栏的时候，悬浮窗可以滑动到状态栏之下，状态栏会遮挡悬浮窗的一部分

### ISSUE THREAD

**Issue by czeall** [princekin-f/EasyFloat#21]
首先跪谢大佬的悬浮窗开源库。
issues:当Activity有状态栏的时候，悬浮窗可以滑动到状态栏之下，状态栏会遮挡悬浮窗的一部分,不知道这个问题大佬是怎么解决的

**Comment by princekin-f** [comment]
如果是系统浮窗，显示活动的可用区域，应该在状态栏的下面。

如果是单页面浮窗，你应该是设置了状态栏沉浸。
因为该模式下：浮窗的可用区域和`setContentView`的区域是一致的，所以悬浮窗也沉浸了。

提供几个参考思路：
- 为浮窗加一个和状态栏同高的透明矩形，这种方式最简单，不过浮窗的触摸区域变大了；
- 从你的描述，这个Activity状态栏沉浸却不透明；如果可以，将这个页面的沉浸效果去除，或者状态栏改为透明；
- 修改拖拽逻辑，将高度的边界最小值，由0改为状态栏高度。
