### ISSUE TITLE
点击事件只能在 touchEvent 里面自己判断吗？

### ISSUE THREAD

**Issue by yuandoudou928** [princekin-f/EasyFloat#210]

**Comment by marco8090** [comment]
touchEvent { view, motionEvent ->
                   //设置点击事件
                    view.setOnClickListener {
                        toStartActivity(xxx::class.java)
                    }
                }

**Comment by dualskana** [comment]
`EasyFloat.with(this)
    .setLayout(R.layout.float_app) {
        // 点击事件
    }
    .registerCallback {
        createResult { isCreated, msg, view ->  }
        show{
            // 点击事件
        }
        hide {  }
        dismiss {  }
        touchEvent { view, motionEvent ->  }
        drag { view, motionEvent ->  }
        dragEnd {  }
    }
    .show()`

**Comment by princekin-f** [comment]
`setLayout`第二个参数可拿到浮窗View：
```
.setLayout(R.layout.float_app) {
    // it 就是浮窗根布局
    it.findViewById<ImageView>(R.id.ivClose).setOnClickListener {
        EasyFloat.dismiss()
    }
}
```
