### ISSUE TITLE
AndroidX 怎么办?

### ISSUE THREAD

**Issue by liuxvdong031** [princekin-f/EasyFloat#22]
项目使用的AndroidX.
集成之后:implementation 'com.github.princekin-f:EasyFloat:1.1.0'
提示:Error: Program type already present: androidx.asynclayoutinflater.view.AsyncLayoutInflater$1
大佬可否提供androidX版本的支持?

**Comment by princekin-f** [comment]
你好，我这边在`AndroidX`中使用是正常的。
- 根据提示应该是`androidx.asynclayoutinflater`这个库依赖重复，可是项目唯一的依赖就是kotlin的jdk；
- 你可以尝试一下，使用最新的`androidx.appcompat:appcompat:1.1.0`；
- 因为我发现使用低版本的`androidx.appcompat`，会额外导入`androidx.asynclayoutinflater`这个库，而使用最新版本不会；
- 是在不行，你使用本地代码试一下。

**Comment by liuxvdong031** [comment]
好的,非常感谢!
