### ISSUE TITLE
嵌套recyclerView并开启拖动，会导致recyclerView本身滑动失效

### ISSUE THREAD

**Issue by yecheng223** [princekin-f/EasyFloat#233]

**Comment by qiupengfei10** [comment]
解决了吗

**Comment by ghost-xx** [comment]
`        tvLog.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                // 处理触摸事件，返回 true 表示事件已处理
                //HookInit.log(HookInit.TAG_MAIN, "触摸事件已处理");
                v.getParent().requestDisallowInterceptTouchEvent(true); // 阻止父视图拦截触摸事件
                return false; // 返回 false 以允许列表控件的滑动
            }
        });
`
