### ISSUE TITLE
请问一下是否有对应java版本

### ISSUE THREAD

**Issue by xsfgdut** [princekin-f/EasyFloat#27]
你好，请问一下你这个工程是否有对应的Java版本支持？
谢谢！

**Comment by princekin-f** [comment]
Java、Kotlin都能用的，使用方式基本一样。

**Comment by zhenlaile** [comment]
java的用不了

**Comment by princekin-f** [comment]
- 项目可以不导入Kotlin
- 但是开发环境需要Kotlin的相关支持
- 在Android Studio的设置中，找到`Plugins`模块，搜索安装`Kotlin`插件就好了
