### ISSUE TITLE
魅族手机，

### ISSUE THREAD

**Issue by MoYuFly** [princekin-f/EasyFloat#3]
fragment.startActivityForResult启动设置页面，会立马在OnActivityResult中响应。

**Comment by princekin-f** [comment]
> fragment.startActivityForResult启动设置页面，会立马在OnActivityResult中响应。

感谢反馈，需要将`MeizuUtils`文件中的`intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`去除，不然会打开新的任务栈，不能进行数据通信。

还有一种解决方案，不使用`onActivityResult`回调，在第二次`onResume`时进行授权结果检测。
