### ISSUE TITLE
请问如何获取拖动后图片的xy轴坐标呢?

### ISSUE THREAD

**Issue by roybill** [princekin-f/EasyFloat#30]
我是通过xml布局加载出来的,想要获取该图片在middle_constraintlayout这个ConstraintLayout布局内的xy轴坐标,而不是整个手机屏幕的坐标
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.appcompat.widget.Toolbar
        android:id="@+id/toolbar_yiyilingqi"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#3300ff00"
        app:layout_constraintTop_toTopOf="parent">

    </androidx.appcompat.widget.Toolbar>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/middle_constraintlayout"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@id/tl_bottom"
        android:background="#330000ff"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@id/toolbar_yiyilingqi">

        <com.lzf.easyfloat.widget.activityfloat.FloatingView
            android:id="@+id/floatingView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <ImageView
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:src="@mipmap/ic_launcher_round" />

        </com.lzf.easyfloat.widget.activityfloat.FloatingView>

    </androidx.constraintlayout.widget.ConstraintLayout>

    <androidx.appcompat.widget.Toolbar
        android:id="@+id/tl_bottom"
        app:layout_constraintBottom_toBottomOf="parent"
        android:layout_width="match_parent"
        android:background="#ffffff"
        android:layout_height="wrap_content">

    </androidx.appcompat.widget.Toolbar>

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by princekin-f** [comment]
- 获取相对于父控件的坐标：`FloatingView.getX()`，`FloatingView.getY()`，此时是视觉上的相对于父控件的位置，是原始坐标加上偏移量。
- `FloatingView.getX() =  getLeft() + getTranslationX()`
- `FloatingView.getY() =  getTop() + getTranslationY()`

更多内容你可以参考[issues 12](https://github.com/princekin-f/EasyFloat/issues/12)里面的文章。

**Comment by roybill** [comment]
请问有没有办法可以直接拿到拖动时每次变化的xy轴坐标值?就类似这个库https://github.com/yhaolpz/FloatWindow的回调函数        public void onPositionUpdate(int x, int y) {
            mXLocation.setText(String.valueOf(x));
            mYLocation.setText(String.valueOf(y));
            //todo:最终的x, y轴坐标
            Log.d(TAG, "1555  onPositionUpdate: x=" + x + " y=" + y);
        }
如果还要我们使用者再花很多时间去获取这些值,那就失去了封装这个库的意义了吧?

**Comment by princekin-f** [comment]
- 你所说的拖拽时每次变化的值是什么，是拖拽过程的坐标信息？还是拖拽结束的坐标信息？
- 如果是上面所说的两种数据，可以使用标准格式，里面的Callback都有实现：
```
    // ps：通过Kotlin DSL实现的回调，可以按需复写方法，用到哪个写哪个
    .registerCallback {
        createResult { isCreated, msg, view ->  }
        show {  }
        hide {  }
        dismiss {  }
        touchEvent { view, motionEvent ->  }
        drag { view, motionEvent ->  }
        dragEnd {  }
    }
```
在Java中使用Kotlin DSL不是很方便，状态回调还有一种常规的接口方式：
```
.registerCallbacks(new OnFloatCallbacks() {
        @Override
        public void createdResult(boolean isCreated, @Nullable String msg, @Nullable View view) { }

        @Override
        public void show(@NotNull View view) { }

        @Override
        public void hide(@NotNull View view) { }

        @Override
        public void dismiss() { }

        @Override
        public void touchEvent(@NotNull View view, @NotNull MotionEvent event) { }

        @Override
        public void drag(@NotNull View view, @NotNull MotionEvent event) { }

        @Override
        public void dragEnd(@NotNull View view) { }
})
```
- 建议您先看一下文档或者demo，毕竟别人的时间也是宝贵的！

**Comment by roybill** [comment]
谢谢,我是这样拿的,再用你的方法优化试试
  FloatingView floatingView = findViewById(R.id.floatingView);
        floatingView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                float xValue = v.getX();    //拖动时的坐标值
                float yValue = v.getY();
                finalX = xValue;
                finalY = yValue;
                mX.setText(String.valueOf(finalX));
                mY.setText(String.valueOf(finalY));
                LogUtil.d("1527  x=" + xValue + "   y=" + yValue);
                return Yiyilingqi.super.onTouchEvent(event);
            }
        });
