### ISSUE TITLE
系统浮窗在底部有一段距离没法拖动下去，这个设置了什么吗？当页浮窗可以到底

### ISSUE THREAD

**Issue by zhoufeng1213** [princekin-f/EasyFloat#32]

**Comment by princekin-f** [comment]
你好，请问你是隐藏了状态栏，还是什么特殊机型？目前发现隐藏状态栏，会出现上述情况。

**Comment by zhoufeng1213** [comment]
华为mate20，没有隐藏状态栏
[](https://github.com/zhoufeng1213/Compressor-master/blob/master/Screenshot_20191112_145414_com.kty.zyy.jpg)

**Comment by zhoufeng1213** [comment]
https://github.com/zhoufeng1213/Compressor-master/blob/master/Screenshot_20191112_145414_com.kty.zyy.jpg

**Comment by princekin-f** [comment]
这是国产全面屏的兼容性问题，做了一些处理，你更新一些试试`v 1.1.3`。

**Comment by zhoufeng1213** [comment]
好的，现在可以了，谢谢

**Comment by zhoufeng1213** [comment]
在小米8上面开启全面屏会还是会出现无法拖动到底部？

**Comment by princekin-f** [comment]
适配了小米全面屏 `v 1.2.1`

**Comment by zhoufeng1213** [comment]
谢谢，已经可以了
