### ISSUE TITLE
Android 8.0以上系统,会提示开启方式不正确   FloatService.kt: 43

### ISSUE THREAD

**Issue by manitozhang** [princekin-f/EasyFloat#33]
java.lang.IllegalStateException:Not allowed to start service Intent { cmp=com.electronic/com.lzf.easyfloat.service.FloatService }: app is in background uid UidRecord{c7d93f0 u0a247 LAST bg:+1m56s623ms idle change:cached procs:2 seq(0,0,0)}

**Comment by princekin-f** [comment]
- 你好，请问是app前台运行时，创建浮窗出现的异常？
- 还是app已经在后台运行，通过相关逻辑创建的系统浮窗？
- `Android 8.0`以后，不允许app后台运行时创建普通Service（后台Service）；如果你需要在后台创建浮窗，可以将浮窗的Service设置为前台Service：
```
// 是否启动前台Service，仅针对系统浮窗；有默认的Notification，可不传
.startForeground(true, floatNotification(this))
```

**Comment by manitozhang** [comment]
好的,非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "刘振峰"<notifications@github.com&gt;; 
发送时间: 2019年11月12日(星期二) 下午2:17
收件人: "princekin-f/EasyFloat"<EasyFloat@noreply.github.com&gt;; 
抄送: "张鹏飞"<1271396448@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [princekin-f/EasyFloat] Android 8.0以上系统,会提示开启方式不正确   FloatService.kt: 43 (#33)



 
你好，请问是app前台运行时，创建浮窗出现的异常？
 
还是app已经在后台运行，通过相关逻辑创建的系统浮窗？
 
Android 8.0以后，不允许app后台运行时创建普通Service（后台Service）；如果你需要在后台创建浮窗，可以将浮窗的Service设置为前台Service：
  // 是否启动前台Service，仅针对系统浮窗；有默认的Notification，可不传 .startForeground(true, floatNotification(this))
