### ISSUE TITLE
过滤Activity时失灵

### ISSUE THREAD

**Issue by Chenshibiao** [princekin-f/EasyFloat#35]
我在自己项目集成，在一个被设置成过滤的Activity里面触发悬浮窗的显示；
说明：activity1：主界面（显示和隐藏的逻辑都在这里）
           activity2：触发界面，被设置成过滤不显示
           activity3：其他界面
bug1： 从1到2，在2里面点击触发，发送EvenBus，1收到后显示；这个时候2并没有被过滤掉。
bug2：退出2回到1，正常显示，重新进入2，发现被过滤了，返回2回到1,1也不显示了，直到进入3，又恢复正常显示。

我在demo上操作上面流程没问题，但是由于我的项目比较复杂，应该是有某些冲突，我该从什么地方入手找原因解决他。谢谢。

**Comment by princekin-f** [comment]
你好，感谢反馈：
#### 针对bug1：
- 浮窗过滤分为两种情况：创建的时候考虑自身是否过滤；切面切换的时候，结合生命周期的判断浮窗的显隐。
- 由于你在2中，通过EventBus在1中创建浮窗，此时只会检查1是否被过滤；
- 此时可以在创建完成时，手动调用隐藏，或者想办法创建的时候传入Activity2的实例。

#### 针对bug2：
- 通过你的描述，应该是2返回1的时候，1没有走`onStart`回调，不知道你的2是不是透明窗口，或者非全屏的窗口，比如Dialog之类的？
- 如果无法让1走`onStart`回调，可以在2返回的时候，手动调一下显示。
