### ISSUE TITLE
创建2个系统悬浮窗失败

### ISSUE THREAD

**Issue by scmyxj** [princekin-f/EasyFloat#36]
EasyFloat.with(activity)
		.setShowPattern(ShowPattern.ALL_TIME)
		.setSidePattern(SidePattern.RESULT_SIDE)
		.setDragEnable(true)
		.setTag(TAG_START)
		.setGravity(Gravity.END | Gravity.CENTER_VERTICAL, 0, 200)
		.setFilter(MainActivity.class)
		.setLayout(R.layout.float_item)                
		.show();

EasyFloat.with(activity)
		.setShowPattern(ShowPattern.ALL_TIME)
		.setSidePattern(SidePattern.RESULT_SIDE)
		.setDragEnable(true)
		.setTag(TAG_END)
		.setGravity(Gravity.END | Gravity.CENTER_VERTICAL, 0, 200)
		.setFilter(MainActivity.class)
		.setLayout(R.layout.float_item)                
		.show();

以上是创建系统悬浮窗的代码，执行时，只能显示最后创建的系统悬浮窗，我也尝试过在两次创建时间增加等待时间，还是不行，大家可以帮看下吗？

**Comment by princekin-f** [comment]
你这是创建了两个一模一样的浮窗吧，貌似两个重叠了，你改一下位置试试。

**Comment by scmyxj** [comment]
我把setGravity的参数改了，还是不行呢？谢谢@princekin-f ，问题还是存在

**Comment by scmyxj** [comment]
大佬，您有空可以试试吗？创建2个系统悬浮窗。

**Comment by princekin-f** [comment]
你用俩按钮，分别调用，看看能不能行？可以的话，再试试：在1创建结果的回调里创建2。

**Comment by scmyxj** [comment]
不行，泪奔

**Comment by princekin-f** [comment]
你之前描述的是同时创建只生成第二个，现在让你分开创建，是什么不行？1不出现？2不出现？还是2出来把1吃掉了？
请确保你两个tag是不同的值。




| |
刘振峰
邮箱：13063218706@163.com
|

签名由 网易邮箱大师 定制

在2019年11月19日 20:05，scmyxj 写道：

不行，泪奔

**Comment by scmyxj** [comment]
问题搞定了，原因如下：
我创建了2个系统悬浮窗，A位于右侧，B位于底部，因为A和B我都设置了setFilter，然后导致了B被隐藏了，现在我把setFilter去掉后就成功了。

**Comment by princekin-f** [comment]
好的
