### ISSUE TITLE
android4.4红米

### ISSUE THREAD

**Issue by songsongtao** [princekin-f/EasyFloat#37]
android4.4红米MIUI9
无法跳转申请权限

**Comment by princekin-f** [comment]
不好意思，我这边没有测试机。
对于这种极端情况，我们可以采取一些折中的方式，比如在创建失败时，提示用户手动去开启权限：
- 在Callback的`createResult`方法中，如果创建失败，并且原因为`系统浮窗权限不足，开启失败`，则进行提示。
