### ISSUE TITLE
Android 10 系统浮窗调用hideappfloat后， 再调用 showappfloat，浮窗无法显示了

### ISSUE THREAD

**Issue by imapach** [princekin-f/EasyFloat#38]
Android 10 系统浮窗调用hideappfloat后， 再调用 showappfloat，浮窗无法显示了

**Comment by princekin-f** [comment]
你的情况应该是：浮窗的管理Service被系统杀死了，导致的管理异常。
目前优化了系统浮窗的管理方式，内部去除了Service，你可以尝试一下最新版。
