### ISSUE TITLE
类似QQ/wx 通知消息屏幕最上方悬浮

### ISSUE THREAD

**Issue by malonecoder** [princekin-f/EasyFloat#39]
大佬你好 ，我想实现一个推送消息来了，在屏幕上方出现一个消息框，前台的，用户点击或触摸就可以自动划上去，控制用户只能往上滑动。这个怎么实现呢

**Comment by princekin-f** [comment]
你好，如果只需要点击时滑上去，相对简单些：设置一下退出动画（默认有），点击时关闭浮窗即可。

如果触摸时控制上滑，则需要重写touch事件，具体又可分为两种实现方式：
- 第一种，重写浮窗内部拖拽逻辑，对竖直方向的拖拽做出反应，实现上下拖动效果，并且保证向下的最大坐标不超过原始y轴坐标；
- 另一种处理方式，只使用浮窗的窗口显示功能，拖拽窗口内部的子View，对子View做拖拽处理，这样对浮窗没有侵入性，不影响浮窗原有的逻辑。

Ps：子View的拖拽需要屏蔽掉浮窗的事件拦截`requestDisallowInterceptTouchEvent(true)`

**Comment by malonecoder** [comment]
感谢大佬才看到~    给产品看说申请权限太重了 让做成页面级别的  切换页面的时候可以让浮窗消失 ，但是在任何一个界面来了推送消息都要显示，这个怎么做合理呢

**Comment by princekin-f** [comment]
可以通过`ActivityLifecycleCallbacks`获取当前Activity的实例，在BaseActivity写具体的方法，传入具体的实例即可。

**Comment by malonecoder** [comment]
谢谢大佬

**Comment by malonecoder** [comment]
![image](https://user-images.githubusercontent.com/26137185/70971294-9cdedf80-20db-11ea-863e-97915ca03af5.png)
在统计后台有的时候报错了 不确定是什么使用场景   使用的activity级别 没有在Application中init

**Comment by malonecoder** [comment]
在dismiss悬浮窗的时候提示parentView没有初始化   AbstractDragFloatingView  - 367行    lazyinit property parentView has not been initialized

**Comment by princekin-f** [comment]
parentView就是activity的根布局，为什么该值会为空不是很明白，但为了代码的健壮做了额外的判断`v 1.2.2`。

**Comment by malonecoder** [comment]
谢谢~~
