### ISSUE TITLE
悬浮窗

### ISSUE THREAD

**Issue by duan759968124** [princekin-f/EasyFloat#4]
您好 您发布的悬浮窗项目 今天用到了  很棒
但是 发现弹框布局中出现的输入框能获取到焦点 但是不能输入  请问这个问题从哪里入手解决。

**Comment by princekin-f** [comment]
> 您好 您发布的悬浮窗项目 今天用到了 很棒
> 但是 发现弹框布局中出现的输入框能获取到焦点 但是不能输入 请问这个问题从哪里入手解决。

你好，首先感谢反馈。
经测试，发现：
1，单页面浮窗，`EditText`正常使用；
2，系统浮窗，出现上述问题；
**3，目前新增了`InputMethodUtils`，在点击`EditText`时，调用`openInputMethod`方法；
4，在软键盘关闭时，调用`closedInputMethod`方法；
5，但暂未提供软键盘的关闭监听方法，需要自行考虑调用时机；**
6，提供一下，APP处于前台时的输入法监听思路：
- 监听页面布局变化，可在`ActivityLifecycleCallbacks`为所有的页面注册布局变化监听。

7，至于APP处于后台时，暂时实在是没思路；
8，至于Google为什么不提供软键盘的相关API，可能是处于安全考虑吧！！！

**Comment by duan759968124** [comment]
谢谢回复，以及提供的解决思路。

**Comment by princekin-f** [comment]
- 最新版本已经解决返回键的问题，多亏了这位大佬的建议：https://github.com/princekin-f/EasyFloat/issues/24
