### ISSUE TITLE
Java版本无法使用dismiss或hide

### ISSUE THREAD

**Issue by liao10108180** [princekin-f/EasyFloat#42]
Java环境无法使用dismiss或hide，我已设置了tag，通过tag调用isShow返回的是false(悬浮窗已显示)

**Comment by liao10108180** [comment]
刚试了浮窗类型为CURRENT_ACTIVITY时候，isShow可以返回true，hide方法也可以使用，但是dismiss还是没效果！其他浮窗类型皆无效果

**Comment by princekin-f** [comment]
你好，我这边试了一下是可以的啊。
- 当页浮窗`ShowPattern.CURRENT_ACTIVITY`（默认模式）的隐藏、显示、销毁方法：
```
EasyFloat.hide()
EasyFloat.show()
EasyFloat.dismiss()
```

- 系统浮窗`ShowPattern.ALL_TIME`、`ShowPattern.FOREGROUND`的隐藏、显示、销毁方法：
```
EasyFloat.hideAppFloat()
EasyFloat.showAppFloat()
EasyFloat.dismissAppFloat()
```

注意区分，调错了没效果的。

**Comment by liao10108180** [comment]
好的，谢谢，没有仔细看文档

**Comment by sd3970566** [comment]
虚拟大师（安卓真机里的 安卓模拟器）
EasyFloat.hideAppFloat()
EasyFloat.showAppFloat()
EasyFloat.dismissAppFloat()失效咋办··

**Comment by fazhongxu** [comment]
错误: 无法访问Unit
找不到kotlin.Unit的类文件  Studio 抽风的情况试过了，重启了，rebuild了，java调用dismiss就会出错，麻烦解决一下，万分感谢感谢感谢

**Comment by threedeer** [comment]
未找到
EasyFloat.hideAppFloat()
EasyFloat.showAppFloat()
EasyFloat.dismissAppFloat()
这系列的方法
版本是最新的2.0.1

**Comment by princekin-f** [comment]
> 未找到
> 
> EasyFloat.hideAppFloat()
> 
> EasyFloat.showAppFloat()
> 
> EasyFloat.dismissAppFloat()
> 
> 这系列的方法
> 
> 版本是最新的2.0.1

最新版直接hide，show，dismiss就行，API整合了
