### ISSUE TITLE
申请悬浮窗权限会导致app奔溃

### ISSUE THREAD

**Issue by liao10108180** [princekin-f/EasyFloat#44]
我进入app悬浮窗权限设置的页面选择允许后，APP会报
 E/InputDispatcher: channel '718ffe2 com.loma.im/com.xxxx.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

然后app重启，是什么原因呢？

**Comment by princekin-f** [comment]
你好，可以提供一下机型信息、安卓版本吗？

**Comment by liao10108180** [comment]
我用的小米6C，系统8.0，java环境

**Comment by princekin-f** [comment]
- 测了8.0的小米6、9.0的小米6，没有出现上述问题；
- 之前做全面屏的适配，测过小米8、小米9，均正常；
- 不知道你这边有没有测别的手机，如果别的手机正常，这可能是该库兼容性的问题；
- 如果别的手机也出现该问题，那应该从你的代码书写找原因了。

**Comment by liao10108180** [comment]
我在app中把easypermissions（https://github.com/googlesamples/easypermissions）设置动态权限的去掉后就不会出现这个问题，具体什么原因导致冲突我还在查

**Comment by liao10108180** [comment]
我发现只要在悬浮窗权限授权之前，操作了其他的动态权限的处理后再去操作悬浮窗权限都会报引起app重启！
