### ISSUE TITLE
这不是bug，这是一个感谢信，哈哈，感谢框架作者

### ISSUE THREAD

**Issue by fazhongxu** [princekin-f/EasyFloat#50]
前两天一直踩坑FloatingWindow框架，好多bug，看到作者这个，今天拿来试试，把前几天的功能基本替换完了，感谢作者，后续我可能会帮助提一些bug，祝开源项目越来越好，2020，💪加油！

**Comment by princekin-f** [comment]
加油，我们一起努力，2020共同进步~
