### ISSUE TITLE
有适配问题，在低版本手机上，全局显示，可以拖动到屏幕底部，在高版本手机上，还有一段距离，就拖不动了

### ISSUE THREAD

**Issue by fazhongxu** [princekin-f/EasyFloat#51]

**Comment by fazhongxu** [comment]
![image](https://user-images.githubusercontent.com/24353536/71869751-28cdaf80-314e-11ea-9ebc-790c8132a8c5.png)    
图1，Android9，OPPO Reno ACE，拖拽到底部一段距离就不动了，我需要拖拽删除


![image](https://user-images.githubusercontent.com/24353536/71869768-37b46200-314e-11ea-8d7b-f724a1626e58.png)
图2  Android6，三星 可以正常拖动到底部

**Comment by fazhongxu** [comment]
框架版本1.2.3

**Comment by princekin-f** [comment]
- 这个是全面屏的适配问题，之前处理过华为和小米的适配；
- 这个问题可以在[`DisplayUtils.isNavigationBarShow`](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/utils/DisplayUtils.kt)进行额外的判断；
- 我这边没有测试机，容我想办法处理一下，或者我们共同解决下。

**Comment by fazhongxu** [comment]
嗯嗯，如何能联系到你，我加下你的微信呗

**Comment by fazhongxu** [comment]
最好是搞一个二维码出来，可以QQ群，微信联系那种，哈哈哈

**Comment by princekin-f** [comment]
哈哈 好的，加我QQ吧，我们组个群。QQ：977208272

**Comment by JarvisBuop** [comment]
感觉这个应该是状态栏高度的原因吧

**Comment by princekin-f** [comment]
最新版已经解决，大家使用新版即可。
