### ISSUE TITLE
dialog背景层遮盖

### ISSUE THREAD

**Issue by zhukai78** [princekin-f/EasyFloat#52]
你好，请问被dialog 的背景阴影遮盖住，怎么样处理？

**Comment by princekin-f** [comment]
你好，请问你是系统浮窗，还是单页面浮窗？
- 如果是系统浮窗，应该不会被遮挡，因为系统浮窗的显示层级高于Dialog；
- 如果是单页面浮窗，浮窗是添加在Activity的根布局的，Dialog作为子窗口，此时是显示在Activity最上层的；
- 如果你想不被Dialog遮挡，请选择系统浮窗。

**Comment by zhukai78** [comment]
看了demo  已解决～～～  谢谢啦
