### ISSUE TITLE
你好，请问我现在通过service来创建一个系统浮窗如何处理？

### ISSUE THREAD

**Issue by ljchengx** [princekin-f/EasyFloat#56]
现在遇见一种情况，通过service来创建弹窗 但是
![image](https://user-images.githubusercontent.com/29397074/73721442-38491400-475f-11ea-8354-b334318defe4.png) 这里withs需要activity上下文 目前没有这个参数。

**Comment by princekin-f** [comment]
- 如果可以的话，你可以把浮窗的创建写在BaseActivity，通过广播去控制；
- 或者`registerActivityLifecycleCallbacks`，通过Application读取当前Activity实例。
