### ISSUE TITLE
dismissAppFloat会偶尔关不掉

### ISSUE THREAD

**Issue by sunlimiter** [princekin-f/EasyFloat#58]
创建并显示float之后不做其他操作，然后执行dismissAppFloat，偶尔会出现悬浮窗未关闭，debug后发现config.isAnim为true，可是我设置了anim为null了setAppFloatAnimator(null)

**Comment by MirkoWu** [comment]
我也是，偶尔dismissAppFloat 失效

**Comment by princekin-f** [comment]
优化了`createdResult`回调，将其放在了浮窗根布局的`onLayout`中，应该解决了此问题。
