### ISSUE TITLE
楼主你好。请问怎么设置弹出位置包含在状态栏

### ISSUE THREAD

**Issue by lidexin-aldelo** [princekin-f/EasyFloat#61]
同title ：楼主你好。请问怎么设置弹出位置包含在状态栏 ，想实现 如下图  红线位置在状态栏上
![image](https://user-images.githubusercontent.com/61337272/75599194-82fb4900-5add-11ea-8a77-7ada158e5c46.png)

**Comment by princekin-f** [comment]
- 你好，系统浮窗的显示位置，是状态栏以下，虚拟导航栏以上；
- 如果想显示在状态栏位置，需要设置浮窗可以延伸到窗口外包`FLAG_LAYOUT_NO_LIMITS`，相关代码在[AppFloatManager.kt](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/widget/appfloat/AppFloatManager.kt)；
- 拖拽和吸附的边界值也需要修改一下，y轴上限由`0`变为`-statusBarHeight`，相关代码在[TouchUtils.kt](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/widget/appfloat/TouchUtils.kt)；
- 如果不需要拖拽和自动吸附，直接设置初始显示位置就行`.setLocation(0, -statusBarHeight)`。

**Comment by cg110902** [comment]
> * 你好，系统浮窗的显示位置，是状态栏以下，虚拟导航栏以上；
> * 如果想显示在状态栏位置，需要设置浮窗可以延伸到窗口外包`FLAG_LAYOUT_NO_LIMITS`，相关代码在[AppFloatManager.kt](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/widget/appfloat/AppFloatManager.kt)；
> * 拖拽和吸附的边界值也需要修改一下，y轴上限由`0`变为`-statusBarHeight`，相关代码在[TouchUtils.kt](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/widget/appfloat/TouchUtils.kt)；
> * 如果不需要拖拽和自动吸附，直接设置初始显示位置就行`.setLocation(0, -statusBarHeight)`。

大佬,具体怎么写改?谢谢

**Comment by princekin-f** [comment]
最简单的方式：https://github.com/princekin-f/EasyFloat/issues/78
