### ISSUE TITLE
你好，建议增加修改系统浮窗UI的方法

### ISSUE THREAD

**Issue by lovedren** [princekin-f/EasyFloat#62]
你好，如何响应外部事件，修改系统浮窗的UI呢，比如接收到广播后浮窗内计时器开启

**Comment by princekin-f** [comment]
- 单页面浮窗`getFloatView`获取浮窗View；
- 系统浮窗`getAppFloatView`获取浮窗View；
- 获取的浮窗View是你设置的布局文件，后续自由操作。

**Comment by lovedren** [comment]
刚试了下，获取浮窗View后可按业务需求修改，非常感谢！
