### ISSUE TITLE
当创建好悬浮窗后，立马调用hide方法无效

### ISSUE THREAD

**Issue by SmartVive** [princekin-f/EasyFloat#67]
EasyFloat.with(this)
                .setLayout(R.layout.layout_float, OnInvokeView {
                    it.setOnClickListener {
                        floatStart()
                    }
                })
                .setShowPattern(ShowPattern.FOREGROUND)
                .setSidePattern(SidePattern.RESULT_HORIZONTAL)
                .setGravity(Gravity.END or Gravity.CENTER_VERTICAL)
                .show()

EasyFloat.hide(activity)

悬浮窗不会隐藏

**Comment by princekin-f** [comment]
.setShowPattern(ShowPattern.FOREGROUND)
是系统浮窗
隐藏系统浮窗需要调用：hideAppFloat

**Comment by SmartVive** [comment]
调用的hideAppFloat 依然不会隐藏

**Comment by SmartVive** [comment]
通过registerCallback去调用hideAppFloat也无效，但是通过线程去延迟执行的话则有效

 .registerCallback {
                    createResult { b, s, view ->
                        EasyFloat.hideAppFloat()
                    }
                }

 Handler(Looper.getMainLooper()).postDelayed({
            EasyFloat.hideAppFloat()
        },500)

**Comment by princekin-f** [comment]
- 你好，对`createdResult`回调进行了优化（`v 1.3.1`）；
- 将回调放在了浮窗根布局的`onLayout`中调用，可以直接在创建结果中进行隐藏；
- 鉴于你创建就进行隐藏，可将出入动画置空，减少性能开销：`.setAppFloatAnimator(null)`。
