### ISSUE TITLE
要是有个XX秒无动作自动贴边隐藏一半到屏幕外的效果就好了。

### ISSUE THREAD

**Issue by sd3970566** [princekin-f/EasyFloat#68]
要是有个XX秒无动作自动贴边隐藏一半到屏幕外的效果就好了。

**Comment by princekin-f** [comment]
这个需求有点小众，暂时自己处理下吧：
- 可以修改吸附源码，额外做些判断；
- 或者关闭原有吸附，在`dragEnd`回调中写一个自己的吸附效果。

**Comment by AlbertZyc** [comment]
写个计时器，回调吸附就行了
