### ISSUE TITLE
在touchevent里设置view.gone报错空指针

### ISSUE THREAD

**Issue by tghjnjvg** [princekin-f/EasyFloat#69]
@Override
                    public void touchEvent(@NotNull View view, @NotNull MotionEvent event) {
                        TextView iv = (TextView) findViewById(R.id.logob);
                        iv.setVisibility(View.GONE);
                    }
这样写报错ttempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
可是R.id.logob是存在的        EasyFloat.with(MainActivity.this)
                .setLayout(R.layout.layout_menu_logoa)
在这个layout里面 
这是怎么回事呢

**Comment by princekin-f** [comment]
通过view获取，view.findViewById(R.id.logob)
