### ISSUE TITLE
怎么动态修改系统悬浮窗的内容

### ISSUE THREAD

**Issue by fjshun** [princekin-f/EasyFloat#7]

**Comment by princekin-f** [comment]
你好，如果想要多个页面控制浮窗里面的试图：
- 建议你把浮窗放在BaseActivity里，
- 把invokeView里面的视图提到BaseActivity里，就可以大家共用了。

**Comment by songsongtao** [comment]
我也遇到了这个问题，而且我是需要在Service里开启悬浮窗，然后动态修改悬浮窗内容，使用非常不方便

**Comment by princekin-f** [comment]
> 我也遇到了这个问题，而且我是需要在Service里开启悬浮窗，然后动态修改悬浮窗内容，使用非常不方便

加了两个API：
- `getFloatView`获取Activity浮窗传入的布局；
- `getAppFloatView`获取系统浮窗传入的布局。
更新一下就可以了。
