### ISSUE TITLE
横竖屏切换位置错乱问题

### ISSUE THREAD

**Issue by pangli** [princekin-f/EasyFloat#70]

**Comment by princekin-f** [comment]
这个需求不固定（比如浮窗在竖屏的底部，并不知横屏需要什么效果），目前只做了旋转保证视图不移动到屏幕外部，屏幕旋转时根据业务需求更新视图即可。

**Comment by pangli** [comment]
那是否有提供旋转时刷新的接口

**Comment by pangli** [comment]
> 这个需求不固定(比如浮窗在竖屏的底部，并不知横屏需要什么效果)，目前只做了旋转保证视图不移动到屏幕外部，屏幕旋转时根据业务需求更新视图即可.

那是否有提供旋转时刷新的接口

**Comment by princekin-f** [comment]
可以使用系统自带的onConfigurationChanged监听

**Comment by diybl** [comment]
> 可以使用系统自带的onConfigurationChanged监听

但是如果悬浮窗是后台 onConfigurationChanged 无法监听到

**Comment by diybl** [comment]
> 可以使用系统自带的onConfigurationChanged监听

后台模式下
用了广播消息 android.intent.action.CONFIGURATION_CHANGED
能监听到消息
但是横屏后 再重新绘制  位置不能靠边 靠到了屏幕正中间。。

**Comment by Continue-po** [comment]
@princekin-f 需求：后台模式，开启悬浮窗。悬浮窗布局里面两个控件，点击任意一个控件切换第三方应用。竖屏切换到横屏的时候，重新绘制，悬浮窗只能拖拽到横屏宽度的一半。这个怎么解决呢？

**Comment by songxiaoliang** [comment]
同样的问题，希望尽快给出解决方案 @princekin-f
