### ISSUE TITLE
建议能新增一个能获取上一次悬浮窗的状态后再前台展示或者后台展示

### ISSUE THREAD

**Issue by chen3441251** [princekin-f/EasyFloat#74]
终于找到一个这么好的浮窗库了，准备使用了，试运行了一下demo，有一个小建议。比如系统浮窗选择仅前台展示，点击open后，再点击hide，推至后台再推到前台，浮窗会自动显示；这里有一个问题就是我是手动hide的，再次推到前台需要展示的时候应该先获取一下之前的状态，如果之前是显示的这个时候可以显示，如果之前是隐藏的那就不展示；这样或许比较好控制一点；目前我如果要实现上面的逻辑的话，我只能用show和dissmiss。每次都是创建一个新的浮窗；

**Comment by chen3441251** [comment]
/**
     * 判断浮窗是否需要隐藏
     */
    private fun checkHide() {
        if (isForeground()) return
        FloatManager.floatMap.forEach { (tag, manager) ->
            // 当app处于后台时，不是仅前台显示的浮窗，都需要显示
            setVisible(manager.config.showPattern != ShowPattern.FOREGROUND, tag)
        }
    }

源码里面的显示判断，建议是再加一个判断是退到后台之前浮窗是什么状态，再次返回前台的时候，如果设置了前台展示&&上一次状态也是展示的，才展示，否则不展示
  setVisible(manager.config.showPattern != ShowPattern.FOREGROUND&&preState==show, tag)

**Comment by princekin-f** [comment]
哈哈，感谢反馈，[FloatConfig.kt](https://github.com/princekin-f/EasyFloat/blob/master/easyfloat/src/main/java/com/lzf/easyfloat/data/FloatConfig.kt) 内部有个字段用来处理该问题的：
```
// 是否需要显示，当过滤信息匹配上时，该值为false（用户手动调用隐藏，该值也为false，相当于手动过滤）
internal var needShow: Boolean = true
```
但是细节处理上有些问题，目前已修复（`v 1.3.2`）。

**Comment by chen3441251** [comment]
谢谢大佬
