### ISSUE TITLE
手机横屏大佬好像没有做啥处理

### ISSUE THREAD

**Issue by SuperRookieMan** [princekin-f/EasyFloat#75]

**Comment by princekin-f** [comment]
只做了视图不移出屏幕的处理，业务需求不确定性大，结合屏幕旋转监听自己处理吧

**Comment by SuperRookieMan** [comment]
问题是全局监听的，在application中而且Activity有自己的横屏逻辑，还有一点横屏完会在中间有时候会在屏幕下面？没有事件可以捕获这个

**Comment by SuperRookieMan** [comment]
用Eventbus 注册下事件然后全局生命周期在监听下横竖只能做隐藏操作感觉不太友好，希望大佬可以后期优化下
