### ISSUE TITLE
AppFloat不显示

### ISSUE THREAD

**Issue by chen3441251** [princekin-f/EasyFloat#77]
我使用该悬浮框的逻辑是：在app初始化的时候就先创建appFloat对象后隐藏，等到要使用的时候再showAppFloat/hideAppFloat去控制;

现象：创建appfloat对象的时候，会自动申请悬浮窗权限，跳转到系统悬浮窗页面，这个时候我忽略不给权限；等到我下一次我需要展示悬浮框的时候，我判断是否有悬浮窗权限，没有就申请，申请成功后showAppFloat。但是这个时候根本就不会展示出来。kotlin代码我看的不是很懂，我推测是不是showAppFloat的时候去判断权限了，如果创建的时候没有权限，就不给展示；即使后面申请权限了，这个控制的字段没有更新，仍然是false，所以展示不出来；
   我也不知道这是不是bug。作者有空看看，做好是在showAppFloat逻辑里面把权限是否申请的字段更新一下，不然我后面某一个时刻已经拿到权限了但是这里还是显示不出来

**Comment by princekin-f** [comment]
- `showAppFloat`是用来设置显隐性的，显示已经创建并且隐藏的系统浮窗；
- 第一次忽略权限，其实浮窗并没有创建；
- 下一次应该执行创建的方法（builder链式调用），并不是`showAppFloat`。

**Comment by chen3441251** [comment]
> * `showAppFloat`是用来设置显隐性的，显示已经创建并且隐藏的系统浮窗；
> * 第一次忽略权限，其实浮窗并没有创建；
> * 下一次应该执行创建的方法（builder链式调用），并不是`showAppFloat`。

好的。我试试
