### ISSUE TITLE
从屏幕顶部向下的动画怎么设置不会被状态栏挡住?

### ISSUE THREAD

**Issue by Ryokooo** [princekin-f/EasyFloat#78]
想要实现类似微信消息提示那样的效果, 但是不能从屏幕最顶部出现而是在状态栏以下

**Comment by princekin-f** [comment]
- 可以占据状态栏的位置，但是浮窗视图层级会在状态栏之下；
- Activity浮窗：设置状态栏沉浸即可，因为浮窗时添加在页面根布局上的；
- 系统浮窗：可以通过位置偏移量来解决，因为系统浮窗的坐标原点是位于状态栏之下的。
```
// 设置系统浮窗位于状态栏位置
.setLocation(0, -DisplayUtils.statusBarHeight(it))
```
