### ISSUE TITLE
系统悬浮窗创建完后怎么去修改里面的文本内容和布局内容？

### ISSUE THREAD

**Issue by fengzhous** [princekin-f/EasyFloat#8]
系统悬浮窗创建完后怎么去修改里面的文本内容和布局内容？
好像现在没这个功能，有没有当系统悬浮窗显示后，我需要修改悬浮窗里面的内容的时候，比如发一个通知，悬浮窗收到通知后立马更改展示的文本内容之类的。

**Comment by princekin-f** [comment]
有两种方案：
- 1，将系统浮窗放到BaseActivity里，把`OnInvokeView`里面的view，提到Activity里；
- 2，新增了两个API（`v 1.0.6`），`getAppFloatView`可用于获取我们传入的布局View。

**Comment by fengzhous** [comment]
感谢添加
