### ISSUE TITLE
全局悬浮窗的时候EditText 的输入法呼出状态下，有没有办法点 空白任意区域取消关闭输入框的输入法状态

### ISSUE THREAD

**Issue by sd3970566** [princekin-f/EasyFloat#85]
全局悬浮窗的时候EditText 的输入法呼出状态下，有没有办法点 空白任意区域取消关闭输入框的输入法状态！  我想点非全局悬浮窗区域关掉输入法。但是不知道怎么实现

**Comment by princekin-f** [comment]
不能，事件监听也监听不到啊。。
