### ISSUE TITLE
设置BACKGROUND 和 ALL_TIME 后台是显示不出来的 

### ISSUE THREAD

**Issue by zguop** [princekin-f/EasyFloat#88]

**Comment by zguop** [comment]
`       EasyFloat.
            with(this)
                .setShowPattern(ShowPattern.BACKGROUND)
                .setSidePattern(SidePattern.RESULT_SIDE)
                .setLayout(R.layout.float_top_dialog,  OnInvokeView {

                })
                .setGravity(Gravity.END)
                .setAppFloatAnimator(null)
                .show()

            finish()`

**Comment by zguop** [comment]
`
         EasyFloat.with(this)
                .setShowPattern(ShowPattern.BACKGROUND)
                .setSidePattern(SidePattern.RESULT_SIDE)
                .setLayout(R.layout.float_top_dialog, OnInvokeView {

                })
                .setGravity(Gravity.END)
                .setAppFloatAnimator(null)
                .show()
            finish()
`

**Comment by princekin-f** [comment]
在Callback看一下`createdResult`，或者将`finish`放到回调中试一下

**Comment by zguop** [comment]
作者有邮箱吗 发个视频给你

**Comment by princekin-f** [comment]
> 作者有邮箱吗 发个视频给你

QQ：977208272
