### ISSUE TITLE
能否添加透过系统悬浮窗点击浮窗下面的按钮API

### ISSUE THREAD

**Issue by fengzhous** [princekin-f/EasyFloat#9]
希望能提供动态修改WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
这样的API。
因为有的浮窗只是展示用，不需要按钮点击。希望能透过浮窗直接点击或滚动浮窗下面的按钮或界面，浮窗不占用浮窗区域的焦点。

**Comment by princekin-f** [comment]
- 可以在`FloatConfig`加一条配置，把`WindowManager.LayoutParams`传过去；
- 目前你先自己处理一下，后续版本看情况考虑是否添加。
