### ISSUE TITLE
自定义view顶部全局显示,怎么让自己定义view沉浸式显示

### ISSUE THREAD

**Issue by xiongxiangdong** [princekin-f/EasyFloat#91]
你好.我想请问一下自定义view顶部全局显示,怎么让自己定义view沉浸式显示.自定义view有背景色.我想让状态栏的颜色跟自定义view的颜色一样.怎么处理.因为那个ParentFrameLayout我获取不了.没法通ParentFrameLayout处理

**Comment by princekin-f** [comment]
- 系统浮窗的窗口范围为：状态栏以下，虚拟导航栏以上；
- 可参考：https://github.com/princekin-f/EasyFloat/issues/61
