### ISSUE TITLE
能否支持悬浮窗拖动到屏幕外

### ISSUE THREAD

**Issue by SheepYang1993** [princekin-f/EasyFloat#94]
为了防止拖出去，拖不回来。
可以支持允许超出屏幕的范围

**Comment by princekin-f** [comment]
需要修改浮窗的flags，以及拖拽范围，参考`AppFloatManager`和`TouchUtils`。

**Comment by SheepYang1993** [comment]
请问修改浮窗的flags是指什么呢？
需要设置什么flaga？
@princekin-f
